### ISSUE TITLE
Global Structured Pruning Pregress

### ISSUE THREAD

**Issue by jsleeg98** [jsleeg98/KD_PaT#2]
# Progress

- [x] ResNet50 구조 분석 #3 
- [x] normalization 방법 고안 https://github.com/jsleeg98/KD_PaT/issues/2#issuecomment-1376499824
- [x] Batch normalization 처리 https://github.com/jsleeg98/KD_PaT/issues/2#issuecomment-1376576962
- [x] layer1 pruning 37a2d89
- [x] layer2 pruning fee664b68856b063afa36248acb568ee4cc33789
- [x] layer3 pruning 2ee102e228b3a628d85b2fa17d284aae7779c267
- [x] layer4 pruning 046936970ae8f7584c285f4068430b1fab0c7c31

**Comment by jsleeg98** [comment]
# Nomalization
- 각 layer 별 필터의 크기가 다를 수 있다. 예를 들어 한 layer는 64x3x3x3이고 다른 layer는 64x1x1x1일 때 이 두 layer의 필터의 크기가 서로 다르기 때문에 norm을 구했을 때 공정한 pruning이 힘들다.
- 따라서 out channel 단위로 L2 norm을 구한 후 필터의 size로 나누어 normalization을 수행한다.

**Comment by jsleeg98** [comment]
# Batch normalization 처리
* 이전 conv layer의 pruning 인덱스와 동일하게 pruning 하였다.
* ResNet50에서는 모든 conv 뒤에 bn이 존재한다.

**Comment by jsleeg98** [comment]
https://github.com/jsleeg98/KD_PaT/issues/2#issuecomment-1376499824

* 깊은 layer일수록 weight의 절대값이 작은 경향이 있다는 것을 확인하였다. 

* Layer-Wise Network Compression Using Gaussian Mixture Model
![image](https://user-images.githubusercontent.com/64693974/211686939-0d71d399-fb18-4100-b1e0-1c47a996f35c.png)

* 직접 시각화하여 확인해볼 필요가 있다.
